#read("./queries/1_all_phone_numbers_of_all_users_including_null.sql")
#read("./queries/2_banana_price_and_weight.sql")
#read("./queries/3_selecting_expensive_banans.sql")
#read("./queries/4_average_banana_weight_in_shelf.sql")
#read("./queries/5_top_10_heaviest_bananas.sql")
#read("./queries/6_supervised_employees_who_did_not_process_an_order.sql")
#read("./queries/7_list_of_all_customers.sql")